### ISSUE TITLE
Create a license for the application

### ISSUE THREAD

**Issue by sjathin** [bhatvineeth/SchedulingSimulation#22]
**Is your feature request related to a problem? Please describe.**
The application is open-sourced and requires a valid license

**Describe the solution you'd like**
Creation of an MIT license

**Additional context**
1. [Licensing a repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository)
2. [Choose an open source license](https://choosealicense.com/)
3. [What you need to know to choose an open source license](https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633)

**Comment by bhatvineeth** [comment]
Included [MIT License](https://github.com/bhatvineeth/SchedulingSimulation/commit/029824b51df153b864b277757430607892ba509a)
