### ISSUE TITLE
Containerise the project with Docker

### ISSUE THREAD

**Issue by bhatvineeth** [bhatvineeth/SchedulingSimulation#25]
**Is your feature request related to a problem? Please describe.**
Setting up docker for the project will help in easy deployment, where multiple steps to setup the project can be avoided. This will help in scaling the project when a frontend component is added and the deployment of that component can be included in the docker.

**Describe the solution you'd like**
Containerise the project with Docker

**Comment by sjathin** [comment]
Fixed by #26
